// prisma/seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create categories first
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'development' },
      update: {},
      create: {
        name: 'Development',
        slug: 'development',
        description: 'Custom web development services for modern businesses',
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: 'maintenance' },
      update: {},
      create: {
        name: 'Maintenance',
        slug: 'maintenance',
        description: 'Ongoing website care and maintenance services',
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: 'troubleshooting' },
      update: {},
      create: {
        name: 'Troubleshooting',
        slug: 'troubleshooting',
        description: 'Technical fixes and problem resolution services',
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: 'graphics-video' },
      update: {},
      create: {
        name: 'Graphics & Video',
        slug: 'graphics-video',
        description: 'Professional design and video creation services',
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: 'digital-marketing' },
      update: {},
      create: {
        name: 'Digital Marketing',
        slug: 'digital-marketing',
        description:
          'Comprehensive digital marketing and advertising solutions',
        isActive: true,
      },
    }),
  ]);

  console.log('✅ Categories created');

  // Find category IDs
  const developmentCategory = categories.find((c) => c.slug === 'development')!;
  const maintenanceCategory = categories.find((c) => c.slug === 'maintenance')!;
  const troubleshootingCategory = categories.find(
    (c) => c.slug === 'troubleshooting',
  )!;
  const graphicsVideoCategory = categories.find(
    (c) => c.slug === 'graphics-video',
  )!;
  const digitalMarketingCategory = categories.find(
    (c) => c.slug === 'digital-marketing',
  )!;

  // Create services
  const services = [
    // DEVELOPMENT SERVICES
    {
      name: 'WordPress Website Development',
      slug: 'wordpress-website-development',
      description:
        'Custom WordPress website development with modern design and functionality. Perfect for businesses looking for a professional online presence with easy content management.',
      shortDesc:
        'Custom WordPress websites with modern design and CMS functionality',
      price: 1299,
      originalPrice: 1799,
      features: [
        'Custom WordPress theme development',
        'Responsive mobile-first design',
        'SEO optimization setup',
        'Contact forms and integrations',
        'Admin training session',
        'Basic plugins installation',
        '30-day post-launch support',
        'Google Analytics setup',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '7-14 days',
      icon: 'Code',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-cyan-500/10',
      guarantees: [
        '100% custom design',
        'Mobile responsive guarantee',
        '30-day bug-free guarantee',
        'SEO-ready structure',
      ],
      bestFor: 'Small to medium businesses needing professional websites',
      categoryId: developmentCategory.id,
    },
    {
      name: 'Headless WordPress with Next.js Development',
      slug: 'headless-wordpress-nextjs-development',
      description:
        'Modern headless WordPress setup with Next.js frontend for lightning-fast performance and superior user experience.',
      shortDesc:
        'High-performance headless WordPress with React/Next.js frontend',
      price: 2499,
      originalPrice: 3299,
      features: [
        'Headless WordPress CMS setup',
        'Next.js React frontend',
        'GraphQL API integration',
        'Server-side rendering (SSR)',
        'Optimized performance',
        'Modern development stack',
        'Deployment setup',
        'Performance monitoring',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '14-21 days',
      icon: 'Zap',
      color: 'from-purple-600 to-purple-700',
      bgGradient: 'from-purple-500/10 via-purple-600/5 to-pink-500/10',
      guarantees: [
        'Lightning-fast performance',
        'Modern tech stack',
        'Scalable architecture',
        '60-day support included',
      ],
      bestFor: 'Businesses requiring high-performance modern websites',
      categoryId: developmentCategory.id,
    },
    {
      name: 'Shopify Store Design & Development',
      slug: 'shopify-store-design-development',
      description:
        'Complete Shopify store setup with custom design, product configuration, and payment integration.',
      shortDesc: 'Full-service Shopify store development and design',
      price: 1799,
      originalPrice: 2499,
      features: [
        'Custom Shopify theme development',
        'Product catalog setup',
        'Payment gateway integration',
        'Shipping configuration',
        'Inventory management setup',
        'SEO optimization',
        'Mobile optimization',
        'Store training session',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '10-14 days',
      icon: 'ShoppingCart',
      color: 'from-green-600 to-green-700',
      bgGradient: 'from-green-500/10 via-green-600/5 to-emerald-500/10',
      guarantees: [
        'Conversion-optimized design',
        'Mobile-first approach',
        'Payment integration guarantee',
        '45-day post-launch support',
      ],
      bestFor: 'E-commerce businesses ready to sell online',
      categoryId: developmentCategory.id,
    },
    {
      name: 'Fullstack Next.js Application Development',
      slug: 'fullstack-nextjs-application-development',
      description:
        'Complete fullstack web application development using Next.js, React, and modern backend technologies.',
      shortDesc:
        'Custom fullstack applications with Next.js and modern tech stack',
      price: 3499,
      originalPrice: 4999,
      features: [
        'Next.js 14+ framework',
        'React frontend development',
        'API routes and backend',
        'Database integration',
        'Authentication system',
        'Responsive design',
        'Deployment and hosting',
        'Performance optimization',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '21-30 days',
      icon: 'Terminal',
      color: 'from-slate-600 to-slate-700',
      bgGradient: 'from-slate-500/10 via-slate-600/5 to-gray-500/10',
      guarantees: [
        'Modern tech stack',
        'Scalable architecture',
        'Performance optimized',
        '90-day warranty',
      ],
      bestFor: 'Startups and businesses needing custom web applications',
      categoryId: developmentCategory.id,
    },
    {
      name: 'MERN Stack Web App Development',
      slug: 'mern-stack-web-app-development',
      description:
        'Full-featured web application development using MongoDB, Express.js, React, and Node.js stack.',
      shortDesc: 'Complete MERN stack applications with modern features',
      price: 2999,
      originalPrice: 3999,
      features: [
        'MongoDB database setup',
        'Express.js backend API',
        'React frontend application',
        'Node.js server environment',
        'User authentication',
        'Real-time features',
        'RESTful API design',
        'Deployment assistance',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '21-30 days',
      icon: 'Database',
      color: 'from-emerald-600 to-emerald-700',
      bgGradient: 'from-emerald-500/10 via-emerald-600/5 to-teal-500/10',
      guarantees: [
        'Full-stack solution',
        'Scalable database design',
        'Modern React features',
        '90-day support',
      ],
      bestFor: 'Complex web applications requiring custom backend',
      categoryId: developmentCategory.id,
    },
    {
      name: 'ReactJS Frontend UI Development',
      slug: 'reactjs-frontend-ui-development',
      description:
        'Professional React.js frontend development with modern UI/UX design and component architecture.',
      shortDesc: 'Modern React.js frontends with beautiful UI/UX design',
      price: 1999,
      originalPrice: 2699,
      features: [
        'React 18+ development',
        'Modern component architecture',
        'State management (Redux/Zustand)',
        'Responsive design system',
        'TypeScript integration',
        'Performance optimization',
        'Testing setup',
        'Documentation',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '14-21 days',
      icon: 'Paintbrush',
      color: 'from-cyan-600 to-cyan-700',
      bgGradient: 'from-cyan-500/10 via-cyan-600/5 to-blue-500/10',
      guarantees: [
        'Modern React patterns',
        'Performance optimized',
        'Cross-browser compatibility',
        '60-day support',
      ],
      bestFor: 'Businesses needing modern frontend interfaces',
      categoryId: developmentCategory.id,
    },
    {
      name: 'Affordable All-in-One Web Development',
      slug: 'affordable-all-in-one-web-development',
      description:
        'Budget-friendly complete web solution including design, development, and basic setup for small businesses.',
      shortDesc:
        'Complete web solution at an affordable price for small businesses',
      price: 79,
      originalPrice: 199,
      features: [
        'Template-based design',
        'Basic customization',
        'Mobile responsive',
        'Contact form setup',
        'Basic SEO setup',
        'Social media integration',
        'Google Analytics',
        '7-day support',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 12 hours',
      completionTime: '3-5 days',
      icon: 'DollarSign',
      color: 'from-orange-600 to-orange-700',
      bgGradient: 'from-orange-500/10 via-orange-600/5 to-red-500/10',
      guarantees: [
        'Budget-friendly solution',
        'Quick turnaround',
        'Mobile responsive',
        'Basic SEO included',
      ],
      bestFor: 'Small businesses with limited budgets',
      categoryId: developmentCategory.id,
    },
    {
      name: 'Complete E-Commerce Launch Package',
      slug: 'complete-ecommerce-launch-package',
      description:
        'Everything you need to launch your online store including design, development, payment setup, and marketing basics.',
      shortDesc: 'Complete e-commerce solution from setup to launch',
      price: 199,
      originalPrice: 399,
      features: [
        'E-commerce platform setup',
        'Product catalog creation',
        'Payment gateway integration',
        'Shipping configuration',
        'Basic inventory management',
        'SEO setup',
        'Social media integration',
        'Launch assistance',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 12 hours',
      completionTime: '5-7 days',
      icon: 'Package',
      color: 'from-pink-600 to-pink-700',
      bgGradient: 'from-pink-500/10 via-pink-600/5 to-rose-500/10',
      guarantees: [
        'Complete launch package',
        'Payment integration',
        'Mobile-optimized store',
        '30-day launch support',
      ],
      bestFor: 'New businesses launching their first online store',
      categoryId: developmentCategory.id,
    },

    // MAINTENANCE SERVICES
    {
      name: 'Ongoing WordPress Maintenance & Updates',
      slug: 'ongoing-wordpress-maintenance-updates',
      description:
        'Monthly WordPress maintenance service including updates, backups, security monitoring, and performance optimization.',
      shortDesc: 'Monthly WordPress care and maintenance service',
      price: 69,
      features: [
        'Monthly core updates',
        'Plugin updates',
        'Theme updates',
        'Weekly backups',
        'Security monitoring',
        'Uptime monitoring',
        'Performance optimization',
        'Monthly reports',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: 'Ongoing',
      icon: 'RefreshCw',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-indigo-500/10',
      guarantees: [
        'Regular maintenance',
        'Proactive monitoring',
        'Emergency support included',
        'Monthly performance reports',
      ],
      bestFor: 'WordPress websites requiring ongoing maintenance',
      categoryId: maintenanceCategory.id,
    },

    // TROUBLESHOOTING SERVICES
    {
      name: 'WordPress Malware Removal',
      slug: 'wordpress-malware-removal',
      description:
        'Professional malware removal service to clean infected WordPress websites and restore security.',
      shortDesc: 'Emergency malware removal and security restoration',
      price: 39,
      originalPrice: 99,
      features: [
        'Complete malware scan',
        'Malware removal',
        'Security hardening',
        'Clean backup restoration',
        'Blacklist check',
        'Basic monitoring',
        'Security report',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: true,
      responseTime: '< 2 hours',
      completionTime: '4-8 hours',
      icon: 'Shield',
      color: 'from-red-600 to-red-700',
      bgGradient: 'from-red-500/10 via-red-600/5 to-orange-500/10',
      guarantees: [
        '100% malware removal',
        'Same-day service',
        '7-day reinfection protection',
        'Security audit included',
      ],
      bestFor: 'Infected WordPress websites needing immediate help',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Blacklist Removal & Reputation Repair',
      slug: 'blacklist-removal-reputation-repair',
      description:
        "Professional blacklist removal service to restore your website's reputation and search engine visibility.",
      shortDesc: 'Remove blacklist warnings and restore website reputation',
      price: 15,
      originalPrice: 49,
      features: [
        'Blacklist status check',
        'Google Safe Browsing removal',
        'Malware cleanup',
        'Reputation monitoring',
        'Search engine notification',
        'Status verification',
        'Prevention setup',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: true,
      responseTime: '< 6 hours',
      completionTime: '12-24 hours',
      icon: 'AlertTriangle',
      color: 'from-rose-600 to-rose-700',
      bgGradient: 'from-rose-500/10 via-rose-600/5 to-red-500/10',
      guarantees: [
        'Blacklist removal',
        'Reputation restoration',
        'Search engine notification',
        'Prevention measures',
      ],
      bestFor: 'Blacklisted websites needing immediate reputation repair',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'WordPress Speed & Performance Optimization',
      slug: 'wordpress-speed-performance-optimization',
      description:
        'Comprehensive WordPress speed optimization to improve loading times and user experience.',
      shortDesc: 'Make your WordPress site lightning fast',
      price: 79,
      originalPrice: 149,
      features: [
        'Performance audit',
        'Image optimization',
        'Caching implementation',
        'Database optimization',
        'Plugin optimization',
        'CDN setup',
        'Minification',
        'Performance report',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '24-48 hours',
      icon: 'Zap',
      color: 'from-yellow-600 to-yellow-700',
      bgGradient: 'from-yellow-500/10 via-yellow-600/5 to-orange-500/10',
      guarantees: [
        'Significant speed improvement',
        'Before/after performance reports',
        'Mobile optimization',
        '30-day optimization guarantee',
      ],
      bestFor: 'Slow WordPress websites needing speed optimization',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Advanced WordPress Security Hardening',
      slug: 'advanced-wordpress-security-hardening',
      description:
        'Comprehensive WordPress security hardening to protect against threats and vulnerabilities.',
      shortDesc: 'Complete WordPress security protection and hardening',
      price: 99,
      originalPrice: 199,
      features: [
        'Security audit',
        'Vulnerability patching',
        'Firewall setup',
        'Login security',
        'File permissions',
        'Security plugins',
        'Monitoring setup',
        'Security report',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '24-48 hours',
      icon: 'Lock',
      color: 'from-indigo-600 to-indigo-700',
      bgGradient: 'from-indigo-500/10 via-indigo-600/5 to-purple-500/10',
      guarantees: [
        'Comprehensive security setup',
        'Vulnerability protection',
        'Ongoing monitoring',
        '60-day security guarantee',
      ],
      bestFor: 'WordPress sites requiring maximum security protection',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Secure Website Migration & Transfer',
      slug: 'secure-website-migration-transfer',
      description:
        'Safe and secure website migration between hosts with zero downtime and data integrity.',
      shortDesc: 'Zero-downtime website migration and hosting transfer',
      price: 29,
      originalPrice: 79,
      features: [
        'Pre-migration backup',
        'DNS management',
        'File transfer',
        'Database migration',
        'Testing verification',
        'SSL transfer',
        'Email setup',
        'Post-migration support',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '24-72 hours',
      icon: 'ArrowRightLeft',
      color: 'from-teal-600 to-teal-700',
      bgGradient: 'from-teal-500/10 via-teal-600/5 to-cyan-500/10',
      guarantees: [
        'Zero data loss',
        'Minimal downtime',
        'Complete functionality',
        '14-day migration support',
      ],
      bestFor: 'Websites needing to change hosting providers',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'SSL Certificate Installation',
      slug: 'ssl-certificate-installation',
      description:
        'Professional SSL certificate installation and configuration for secure website connections.',
      shortDesc: 'Secure your website with SSL certificate installation',
      price: 29,
      originalPrice: 59,
      features: [
        'SSL certificate purchase',
        'Installation and configuration',
        'HTTPS redirect setup',
        'Mixed content fixes',
        'Browser verification',
        'Auto-renewal setup',
        'Security testing',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 12 hours',
      completionTime: '12-24 hours',
      icon: 'Lock',
      color: 'from-green-600 to-green-700',
      bgGradient: 'from-green-500/10 via-green-600/5 to-emerald-500/10',
      guarantees: [
        'Proper SSL installation',
        'Browser security verification',
        'HTTPS redirect setup',
        '30-day installation support',
      ],
      bestFor: 'Websites needing secure HTTPS connections',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Fix 404 Not Found Errors',
      slug: 'fix-404-not-found-errors',
      description:
        'Identify and fix 404 not found errors to improve user experience and SEO rankings.',
      shortDesc: 'Eliminate 404 errors and improve website navigation',
      price: 29,
      originalPrice: 69,
      features: [
        '404 error audit',
        'Broken link identification',
        'Redirect implementation',
        'Custom 404 page',
        'Internal link fixes',
        'SEO impact assessment',
        'Testing verification',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '24-48 hours',
      icon: 'Search',
      color: 'from-orange-600 to-orange-700',
      bgGradient: 'from-orange-500/10 via-orange-600/5 to-yellow-500/10',
      guarantees: [
        'All 404 errors fixed',
        'Proper redirects setup',
        'Custom 404 page',
        '30-day error monitoring',
      ],
      bestFor: 'Websites with broken links and navigation issues',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Resolve Email Deliverability Issues',
      slug: 'resolve-email-deliverability-issues',
      description:
        'Fix email delivery problems and improve inbox delivery rates for your website emails.',
      shortDesc: 'Fix email delivery problems and improve inbox rates',
      price: 49,
      originalPrice: 99,
      features: [
        'Email deliverability audit',
        'SMTP configuration',
        'SPF/DKIM setup',
        'DMARC implementation',
        'Spam testing',
        'Email authentication',
        'Delivery monitoring',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '24-48 hours',
      icon: 'Mail',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-indigo-500/10',
      guarantees: [
        'Improved delivery rates',
        'Proper email authentication',
        'Spam folder avoidance',
        '30-day delivery monitoring',
      ],
      bestFor: 'Websites with email delivery and spam issues',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Fix 500 Internal Server Errors',
      slug: 'fix-500-internal-server-errors',
      description:
        'Diagnose and fix 500 internal server errors to restore website functionality.',
      shortDesc: 'Emergency fix for 500 internal server errors',
      price: 29,
      originalPrice: 79,
      features: [
        'Error log analysis',
        'Root cause identification',
        'Server configuration fix',
        'Plugin conflict resolution',
        'File permission correction',
        'Database repair',
        'Functionality testing',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: true,
      responseTime: '< 2 hours',
      completionTime: '2-6 hours',
      icon: 'AlertTriangle',
      color: 'from-red-600 to-red-700',
      bgGradient: 'from-red-500/10 via-red-600/5 to-orange-500/10',
      guarantees: [
        'Complete error resolution',
        'Root cause elimination',
        'Functionality restoration',
        '14-day error-free guarantee',
      ],
      bestFor: 'Websites experiencing critical 500 server errors',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Fix 403 Forbidden Errors',
      slug: 'fix-403-forbidden-errors',
      description:
        'Resolve 403 forbidden access errors and restore proper website permissions.',
      shortDesc: 'Fix access denied errors and permission issues',
      price: 29,
      originalPrice: 69,
      features: [
        'Permission audit',
        'File permission correction',
        'Server configuration fix',
        'Access rule review',
        'Security settings adjustment',
        'Testing verification',
        'Prevention setup',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 12 hours',
      completionTime: '12-24 hours',
      icon: 'ShieldAlert',
      color: 'from-amber-600 to-amber-700',
      bgGradient: 'from-amber-500/10 via-amber-600/5 to-orange-500/10',
      guarantees: [
        'Complete access restoration',
        'Proper permissions setup',
        'Security maintained',
        '30-day access guarantee',
      ],
      bestFor: 'Websites with access permission problems',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Mixed Content SSL Fix',
      slug: 'mixed-content-ssl-fix',
      description:
        'Fix mixed content warnings on SSL-enabled websites for full HTTPS security.',
      shortDesc: 'Eliminate mixed content warnings for full SSL security',
      price: 29,
      originalPrice: 59,
      features: [
        'Mixed content audit',
        'HTTP to HTTPS conversion',
        'Image source updates',
        'Script source fixes',
        'CSS reference updates',
        'Browser warning elimination',
        'Security verification',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '12-24 hours',
      icon: 'Shield',
      color: 'from-emerald-600 to-emerald-700',
      bgGradient: 'from-emerald-500/10 via-emerald-600/5 to-green-500/10',
      guarantees: [
        'All mixed content fixed',
        'Full HTTPS security',
        'Browser warning removal',
        '30-day content monitoring',
      ],
      bestFor: 'SSL websites with mixed content security warnings',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'White Screen of Death (WSOD) Recovery',
      slug: 'white-screen-of-death-wsod-recovery',
      description:
        'Emergency recovery service for WordPress white screen of death errors.',
      shortDesc: 'Emergency fix for WordPress white screen errors',
      price: 29,
      originalPrice: 79,
      features: [
        'Error diagnosis',
        'Memory limit increase',
        'Plugin deactivation',
        'Theme switching',
        'Error log analysis',
        'Site restoration',
        'Prevention measures',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: true,
      responseTime: '< 2 hours',
      completionTime: '2-6 hours',
      icon: 'MonitorSpeaker',
      color: 'from-slate-600 to-slate-700',
      bgGradient: 'from-slate-500/10 via-slate-600/5 to-gray-500/10',
      guarantees: [
        'Complete site recovery',
        'Error elimination',
        'Functionality restoration',
        '14-day stability guarantee',
      ],
      bestFor: 'WordPress sites showing white screen errors',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'Fix Error Establishing Database Connection',
      slug: 'fix-error-establishing-database-connection',
      description:
        'Resolve database connection errors and restore website database connectivity.',
      shortDesc: 'Fix database connection errors and restore site access',
      price: 25,
      originalPrice: 69,
      features: [
        'Database connection diagnosis',
        'Credential verification',
        'Database server check',
        'Configuration file repair',
        'Connection testing',
        'Database optimization',
        'Backup verification',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: true,
      responseTime: '< 2 hours',
      completionTime: '2-4 hours',
      icon: 'Database',
      color: 'from-cyan-600 to-cyan-700',
      bgGradient: 'from-cyan-500/10 via-cyan-600/5 to-blue-500/10',
      guarantees: [
        'Database connection restored',
        'Site functionality recovery',
        'Data integrity verified',
        '14-day connection stability',
      ],
      bestFor: 'Websites with database connection failures',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'DNS Configuration & Issue Resolution',
      slug: 'dns-configuration-issue-resolution',
      description:
        'Professional DNS setup and troubleshooting for proper domain name resolution.',
      shortDesc: 'Fix DNS issues and configure proper domain resolution',
      price: 49,
      originalPrice: 99,
      features: [
        'DNS audit and analysis',
        'DNS record configuration',
        'Nameserver setup',
        'Propagation monitoring',
        'Email DNS setup',
        'Subdomain configuration',
        'Global DNS testing',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 12 hours',
      completionTime: '12-24 hours',
      icon: 'Globe',
      color: 'from-violet-600 to-violet-700',
      bgGradient: 'from-violet-500/10 via-violet-600/5 to-purple-500/10',
      guarantees: [
        'Proper DNS configuration',
        'Global accessibility',
        'Email delivery setup',
        '30-day DNS monitoring',
      ],
      bestFor: 'Websites with domain and DNS resolution issues',
      categoryId: troubleshootingCategory.id,
    },
    {
      name: 'WordPress Rescue & Repair Service',
      slug: 'wordpress-rescue-repair-service',
      description:
        'Comprehensive WordPress rescue service for severely damaged or compromised websites.',
      shortDesc: 'Complete WordPress recovery and repair service',
      price: 49,
      originalPrice: 129,
      features: [
        'Complete site diagnosis',
        'Backup recovery',
        'Malware removal',
        'Database repair',
        'File restoration',
        'Plugin/theme fixes',
        'Security hardening',
        'Functionality testing',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: true,
      responseTime: '< 4 hours',
      completionTime: '4-12 hours',
      icon: 'Wrench',
      color: 'from-indigo-600 to-indigo-700',
      bgGradient: 'from-indigo-500/10 via-indigo-600/5 to-blue-500/10',
      guarantees: [
        'Complete site recovery',
        'Full functionality restoration',
        'Security improvement',
        '30-day stability guarantee',
      ],
      bestFor: 'Severely damaged WordPress websites needing rescue',
      categoryId: troubleshootingCategory.id,
    },

    // GRAPHICS & VIDEO SERVICES
    {
      name: 'Custom Logo Design',
      slug: 'custom-logo-design',
      description:
        'Professional custom logo design that perfectly represents your brand identity and values.',
      shortDesc: 'Professional custom logo design for your brand',
      price: 199,
      originalPrice: 399,
      features: [
        '5 initial logo concepts',
        '3 rounds of revisions',
        'Vector files (AI, EPS)',
        'PNG and JPG formats',
        'Brand color palette',
        'Typography recommendations',
        'Usage guidelines',
        'Social media variants',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '5-7 days',
      icon: 'Palette',
      color: 'from-pink-600 to-pink-700',
      bgGradient: 'from-pink-500/10 via-pink-600/5 to-rose-500/10',
      guarantees: [
        '100% original design',
        'Multiple concept options',
        'Vector file delivery',
        'Unlimited minor revisions',
      ],
      bestFor: 'Businesses needing professional brand identity',
      categoryId: graphicsVideoCategory.id,
    },
    {
      name: 'Professional Brochure Design',
      slug: 'professional-brochure-design',
      description:
        'Eye-catching brochure designs that effectively communicate your message and attract customers.',
      shortDesc: 'Professional marketing brochures that convert',
      price: 149,
      originalPrice: 299,
      features: [
        'Custom brochure design',
        'Tri-fold or bi-fold options',
        'Print-ready files',
        'High-resolution output',
        'Brand integration',
        '2 rounds of revisions',
        'Multiple format delivery',
        'Printing recommendations',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '3-5 days',
      icon: 'FileText',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-cyan-500/10',
      guarantees: [
        'Professional design quality',
        'Print-ready output',
        'Brand consistency',
        'Revision satisfaction',
      ],
      bestFor: 'Businesses needing marketing materials',
      categoryId: graphicsVideoCategory.id,
    },
    {
      name: 'Social Video Ads & Reels Creation',
      slug: 'social-video-ads-reels-creation',
      description:
        'Engaging video content creation for social media advertising and organic reach.',
      shortDesc: 'Engaging video content for social media marketing',
      price: 299,
      originalPrice: 499,
      features: [
        '3 video concepts',
        'Professional editing',
        'Motion graphics',
        'Brand integration',
        'Multiple format export',
        'Platform optimization',
        'Music and sound effects',
        'Call-to-action integration',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '5-7 days',
      icon: 'Video',
      color: 'from-purple-600 to-purple-700',
      bgGradient: 'from-purple-500/10 via-purple-600/5 to-pink-500/10',
      guarantees: [
        'Engaging video content',
        'Platform-optimized formats',
        'Professional quality',
        '2 rounds of revisions',
      ],
      bestFor: 'Businesses focusing on video marketing',
      categoryId: graphicsVideoCategory.id,
    },

    // DIGITAL MARKETING SERVICES
    {
      name: 'Backlink Building Service',
      slug: 'backlink-building-service',
      description:
        "High-quality backlink building to improve your website's domain authority and search rankings.",
      shortDesc: 'Quality backlinks to boost your search rankings',
      price: 299,
      originalPrice: 499,
      features: [
        'High DA backlink acquisition',
        'Manual outreach',
        'Content-based link building',
        'Competitor analysis',
        'Monthly reporting',
        'White-hat techniques only',
        'Link quality verification',
        'Ongoing monitoring',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '30 days ongoing',
      icon: 'Link',
      color: 'from-green-600 to-green-700',
      bgGradient: 'from-green-500/10 via-green-600/5 to-emerald-500/10',
      guarantees: [
        'High-quality backlinks only',
        'White-hat SEO practices',
        'Monthly progress reports',
        'Penalty-safe methods',
      ],
      bestFor: 'Websites needing improved domain authority',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'Local SEO Optimization',
      slug: 'local-seo-optimization',
      description:
        'Complete local SEO optimization to improve visibility in local search results.',
      shortDesc: 'Dominate local search results in your area',
      price: 199,
      originalPrice: 399,
      features: [
        'Google My Business optimization',
        'Local keyword research',
        'Citation building',
        'Review management setup',
        'Local schema markup',
        'NAP consistency',
        'Local content strategy',
        'Monthly local reports',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '14-21 days',
      icon: 'MapPin',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-indigo-500/10',
      guarantees: [
        'Improved local visibility',
        'Google My Business optimization',
        'Citation consistency',
        '60-day ranking improvement',
      ],
      bestFor: 'Local businesses wanting more local customers',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'E-commerce SEO Services',
      slug: 'ecommerce-seo-services',
      description:
        'Specialized SEO optimization for online stores to increase product visibility and sales.',
      shortDesc: 'SEO optimization specifically for online stores',
      price: 399,
      originalPrice: 699,
      features: [
        'Product page optimization',
        'Category page SEO',
        'Technical SEO audit',
        'Schema markup implementation',
        'Site speed optimization',
        'Mobile SEO',
        'Conversion optimization',
        'Monthly SEO reports',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '21-30 days',
      icon: 'ShoppingBag',
      color: 'from-emerald-600 to-emerald-700',
      bgGradient: 'from-emerald-500/10 via-emerald-600/5 to-green-500/10',
      guarantees: [
        'Improved product visibility',
        'Technical SEO optimization',
        'Conversion rate improvement',
        '90-day ranking guarantee',
      ],
      bestFor: 'Online stores needing more organic traffic',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'Technical SEO Audit & Fixes',
      slug: 'technical-seo-audit-fixes',
      description:
        'Comprehensive technical SEO audit and implementation of fixes to improve search performance.',
      shortDesc: 'Complete technical SEO audit and optimization',
      price: 249,
      originalPrice: 449,
      features: [
        'Complete technical SEO audit',
        'Crawl error fixes',
        'Site speed optimization',
        'Mobile-friendliness',
        'Schema markup',
        'XML sitemap optimization',
        'Robots.txt optimization',
        'Detailed audit report',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '14-21 days',
      icon: 'Search',
      color: 'from-orange-600 to-orange-700',
      bgGradient: 'from-orange-500/10 via-orange-600/5 to-red-500/10',
      guarantees: [
        'Comprehensive audit',
        'All technical issues fixed',
        'Performance improvement',
        '60-day optimization support',
      ],
      bestFor: 'Websites with technical SEO problems',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'Google Ads Campaign Management',
      slug: 'google-ads-campaign-management',
      description:
        'Professional Google Ads campaign setup and management to maximize ROI and conversions.',
      shortDesc: 'Professional Google Ads campaign setup and optimization',
      price: 499,
      originalPrice: 799,
      features: [
        'Campaign strategy development',
        'Keyword research & selection',
        'Ad copy creation',
        'Landing page optimization',
        'Bid management',
        'A/B testing setup',
        'Conversion tracking',
        'Monthly performance reports',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '7-10 days setup',
      icon: 'Target',
      color: 'from-red-600 to-red-700',
      bgGradient: 'from-red-500/10 via-red-600/5 to-orange-500/10',
      guarantees: [
        'Professional campaign setup',
        'ROI optimization',
        'Transparent reporting',
        '30-day performance guarantee',
      ],
      bestFor: 'Businesses wanting immediate online visibility',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'Meta (Facebook & Instagram) Ads Management',
      slug: 'meta-facebook-instagram-ads-management',
      description:
        'Expert Facebook and Instagram advertising campaign management for social media success.',
      shortDesc: 'Expert Facebook and Instagram advertising campaigns',
      price: 399,
      originalPrice: 699,
      features: [
        'Audience research & targeting',
        'Creative development',
        'Campaign optimization',
        'A/B testing',
        'Pixel setup & tracking',
        'Retargeting campaigns',
        'Performance monitoring',
        'Monthly strategy reports',
      ],
      isActive: true,
      isPopular: true,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '5-7 days setup',
      icon: 'Users',
      color: 'from-blue-600 to-blue-700',
      bgGradient: 'from-blue-500/10 via-blue-600/5 to-indigo-500/10',
      guarantees: [
        'Expert audience targeting',
        'Creative optimization',
        'Performance tracking',
        '30-day campaign optimization',
      ],
      bestFor: 'Businesses targeting social media audiences',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'TikTok Ads Creation & Promotion',
      slug: 'tiktok-ads-creation-promotion',
      description:
        'Creative TikTok advertising campaigns designed to engage younger demographics effectively.',
      shortDesc: 'Engaging TikTok ads for younger demographics',
      price: 349,
      originalPrice: 599,
      features: [
        'TikTok-native content creation',
        'Trending hashtag research',
        'Influencer collaboration',
        'Video ad optimization',
        'Audience targeting',
        'Performance tracking',
        'Viral content strategy',
        'Weekly performance reports',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '7-10 days',
      icon: 'Music',
      color: 'from-pink-600 to-pink-700',
      bgGradient: 'from-pink-500/10 via-pink-600/5 to-purple-500/10',
      guarantees: [
        'Platform-native content',
        'Trend-based strategy',
        'Engagement optimization',
        '30-day campaign support',
      ],
      bestFor: 'Brands targeting Gen Z and millennial audiences',
      categoryId: digitalMarketingCategory.id,
    },
    {
      name: 'LinkedIn B2B Ads Strategy & Management',
      slug: 'linkedin-b2b-ads-strategy-management',
      description:
        'Professional LinkedIn advertising for B2B lead generation and business growth.',
      shortDesc: 'Professional LinkedIn B2B advertising and lead generation',
      price: 599,
      originalPrice: 999,
      features: [
        'B2B audience targeting',
        'Lead generation strategy',
        'Professional content creation',
        'InMail campaigns',
        'LinkedIn pixel setup',
        'Lead nurturing sequences',
        'ROI tracking',
        'Monthly B2B reports',
      ],
      isActive: true,
      isPopular: false,
      isUrgent: false,
      responseTime: '< 24 hours',
      completionTime: '10-14 days',
      icon: 'Briefcase',
      color: 'from-indigo-600 to-indigo-700',
      bgGradient: 'from-indigo-500/10 via-indigo-600/5 to-blue-500/10',
      guarantees: [
        'B2B-focused strategy',
        'Quality lead generation',
        'Professional targeting',
        '60-day lead quality guarantee',
      ],
      bestFor: 'B2B companies seeking professional leads',
      categoryId: digitalMarketingCategory.id,
    },
  ];

  console.log('🌱 Creating services...');

  // Create services in batches to avoid overwhelming the database
  const batchSize = 5;
  for (let i = 0; i < services.length; i += batchSize) {
    const batch = services.slice(i, i + batchSize);
    await Promise.all(
      batch.map((service) =>
        prisma.service.upsert({
          where: { slug: service.slug },
          update: service,
          create: service,
        }),
      ),
    );
    console.log(
      `✅ Created services batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(services.length / batchSize)}`,
    );
  }

  console.log('🎉 Seeding completed successfully!');
  console.log(
    `📊 Created ${categories.length} categories and ${services.length} services`,
  );
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
